In [1]:
import numpy as np

In [2]:
x=np.array([[1,2,3],[4,5,6]])

In [3]:
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


In [4]:
from scipy import sparse

In [5]:
eye=np.eye(4)

In [6]:
print("Numpy array:\n{}".format(eye))

Numpy array:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
